### ISSUE TITLE
decoding problem

### ISSUE THREAD

**Issue by atroopa** [SILI1994/Structured-light-stereo#2]
I checked your code carefully. In the decoding section, only the gray_code_decoder_disp.py file
Function. The rest of the files show this error after execution.
Traceback (most recent call last):
   File "C:/Users/APA/PycharmProjects/pythonProjectOpen3D/Structured-light-stereo-main/gray_code_decoder_tria_unique_pts.py", line 121, in <module>
     error, projPixel = graycode.getProjPixel(pattern_list[0], j, i)
TypeError: Required argument 'projPix' (pos 4) not found

Process finished with exit code 1
In addition, and most importantly, the output file cannot be converted into a mesh. My goal is to use your code to convert the decode of the bag into an .obj file and display it in my program through Mashlab.

**Comment by feiran-l** [comment]
I cannot reproduce the error at my side. Have you installed the proper version of OPENCV noted in the readme? Also, point cloud is the raw format for structured light systems. If you want a mesh, I'm afraid you have to extract normals and do surface reconstruction (e.g., check OPEN3D's Poisson surface reconstruction) by yourself.

**Comment by atroopa** [comment]
I need an example code to display the mesh no matter what library it is from. I prefer to use pyvista, can you generate this code and add it to your useful repository?

**Comment by feiran-l** [comment]
I have made some quick tests with [OPEN3D](http://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html)'s surface reconstruction methods and found it doesn't work well on the example bag data. I guess this is mainly because surface reconstruction ideally requires a watertight shape while the bag data here is not (it also contains some background that needs to be removed). So I'm afraid there is not many things I can do with this specific bag data.
