### ISSUE TITLE
Scalloped dots in the point cloud!

### ISSUE THREAD

**Issue by cagataykrdmr** [SILI1994/Structured-light-stereo#4]
Hello, I am generating point cloud data with my own images using gray_code_decoder_disp.py. But the point cloud is scalloped as seen in the photo. In other words, it consists of many small squares parallel to the plane of the camera.

Point Cloud Photos:

Full cloud:  https://ibb.co/bWGD1DX
Zoom to small squares : https://ibb.co/f1TMFQc
Zoom squares side view: https://ibb.co/tL9xdqw

Even though the surface of the piece I scanned is completely smooth and flat, the point cloud is formed in this way.

**Comment by feiran-l** [comment]
Sorry I totally missed this issue. I guess this problem is due to the stereo system's depth resolution. According to the stereo formula $z=bf/d$, when the focal length $f$ is fixed, given a unit of disparity $d$, the depth resolution is related to the baseline $b$. I.e., if you want the surface to be more smooth, you may need to narrow down the baseline.
